//------------------------------------------------------------------------------
// <auto-generated>
//     Bu kod araç tarafından oluşturuldu.
//
//     Bu dosyada yapılacak değişiklikler yanlış davranışa neden olabilir ve
//     kod yeniden üretildiğinde kaybolur.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{


    public partial class depo_ve_sevkiyat_yonetim_yazilimi
    {
    }
}
